/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import static finalproject.Theater.getInstance;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author karim
 */
public class mainPage extends javax.swing.JFrame {

    private String userEmail = "NONE";
    private String usersFirstName;
    private String usersLastName;
    private String usersPassword;
    private ArrayList<Movie> movies;
    
    public mainPage() {
        try{
           Theater theater = getInstance();
           movies = theater.getMovies();
        }catch(SQLException e){e.printStackTrace();}
        initComponents();
        String temp;
        DefaultListModel movie = new DefaultListModel();
        movieList.setModel(movie);
        for (int i = 0; i < movies.size(); i++) {
            temp = movies.get(i).getMovieName();
            movie.addElement(temp);
        }
    }
    
    public mainPage(String userEMAIL) {
        try{
           Theater theater = getInstance();
           movies = theater.getMovies();
        }catch(SQLException e){e.printStackTrace();}
        userEmail = userEMAIL;
        initComponents();
        String temp;
        DefaultListModel movie = new DefaultListModel();
        movieList.setModel(movie);
        for (int i = 0; i < movies.size(); i++) {
            temp = movies.get(i).getMovieName();
            movie.addElement(temp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        userButton = new javax.swing.JButton();
        RBMovie = new javax.swing.JRadioButton();
        CAButton = new javax.swing.JRadioButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        SMDisplay = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        movieList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        selectMovieBtn = new javax.swing.JButton();
        cancelTicketButton = new javax.swing.JButton();
        CADisplay = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        accouncementsList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        showTimesDisplay = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        movieNameLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        showTimeList = new javax.swing.JList<>();
        selectShowTime = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(504, 52));

        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userIcon.png"))); // NOI18N
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBMovie);
        RBMovie.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        RBMovie.setText("Select Movie");
        RBMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMovieActionPerformed(evt);
            }
        });

        buttonGroup1.add(CAButton);
        CAButton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        CAButton.setText("Check Announcements");
        CAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBMovie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(userButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RBMovie)
                        .addComponent(CAButton))
                    .addComponent(userButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setBackground(new java.awt.Color(255, 204, 204));

        SMDisplay.setBackground(new java.awt.Color(255, 204, 204));

        movieList.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        movieList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        movieList.setMaximumSize(new java.awt.Dimension(100, 100));
        movieList.setMinimumSize(new java.awt.Dimension(100, 100));
        movieList.setName(""); // NOI18N
        jScrollPane1.setViewportView(movieList);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Select a Movie");

        selectMovieBtn.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        selectMovieBtn.setText("Select");
        selectMovieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMovieBtnActionPerformed(evt);
            }
        });

        cancelTicketButton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        cancelTicketButton.setText("Cancel Ticket");
        cancelTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTicketButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SMDisplayLayout = new javax.swing.GroupLayout(SMDisplay);
        SMDisplay.setLayout(SMDisplayLayout);
        SMDisplayLayout.setHorizontalGroup(
            SMDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SMDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SMDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(SMDisplayLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(SMDisplayLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(selectMovieBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelTicketButton)
                .addGap(100, 100, 100))
        );
        SMDisplayLayout.setVerticalGroup(
            SMDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SMDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(SMDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectMovieBtn)
                    .addComponent(cancelTicketButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        CADisplay.setBackground(new java.awt.Color(255, 204, 204));
        CADisplay.setPreferredSize(new java.awt.Dimension(492, 513));

        accouncementsList.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        accouncementsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "NEW JAWS ", "MOVIE JUST RELEASED", "NEW CARS", "MOVIE JUST RELEASED", "IF YOU WANT EARLY", "INFO ON UPCOMING", "MOVIES REGISTER NOW!" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(accouncementsList);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Announcements:");

        javax.swing.GroupLayout CADisplayLayout = new javax.swing.GroupLayout(CADisplay);
        CADisplay.setLayout(CADisplayLayout);
        CADisplayLayout.setHorizontalGroup(
            CADisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CADisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CADisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(CADisplayLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 215, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CADisplayLayout.setVerticalGroup(
            CADisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CADisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        showTimesDisplay.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel3.setText("Show Times for:");

        movieNameLabel.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N

        showTimeList.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jScrollPane3.setViewportView(showTimeList);

        selectShowTime.setText("Select");
        selectShowTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectShowTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout showTimesDisplayLayout = new javax.swing.GroupLayout(showTimesDisplay);
        showTimesDisplay.setLayout(showTimesDisplayLayout);
        showTimesDisplayLayout.setHorizontalGroup(
            showTimesDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showTimesDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showTimesDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(showTimesDisplayLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieNameLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(showTimesDisplayLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(selectShowTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        showTimesDisplayLayout.setVerticalGroup(
            showTimesDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showTimesDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showTimesDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(movieNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectShowTime)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(SMDisplay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(CADisplay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(showTimesDisplay, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SMDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CADisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(showTimesDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SMDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CADisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(showTimesDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        if (userEmail.equals("NONE")) {
            guestInfoPage g = new guestInfoPage();
            g.setLocationRelativeTo(null);
            g.setVisible(true);
            dispose();
        } else {
            try {
                DBConnection connection = new DBConnection("jdbc:mysql://localhost/MovieTheater","root","Shark.Killer572908");
                connection.initializeConnection();
                usersFirstName = connection.getUsersFirstName(userEmail);
                usersLastName = connection.getUsersLastName(userEmail);
                usersPassword = connection.getUserPass(userEmail);
            } catch(SQLException e){e.printStackTrace();}
            userInfoPage u = new userInfoPage(userEmail, usersFirstName, usersLastName, usersPassword);
            u.setLocationRelativeTo(null);
            u.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_userButtonActionPerformed

    private void RBMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMovieActionPerformed
        SMDisplay.setVisible(true);
        CADisplay.setVisible(false);
        showTimesDisplay.setVisible(false);
    }//GEN-LAST:event_RBMovieActionPerformed

    private void CAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAButtonActionPerformed
        SMDisplay.setVisible(false);
        CADisplay.setVisible(true);
        showTimesDisplay.setVisible(false);
    }//GEN-LAST:event_CAButtonActionPerformed

    private void selectMovieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMovieBtnActionPerformed
        String movieName = movieList.getSelectedValue();
        int index = -1;
        for (int i = 0; i < movies.size(); i++) {
            if (movieName.equals(movies.get(i).getMovieName())) {
                index = i;
            }
        }
        Movie actualMovie = movies.get(index);
        Showtimes temp;
        String show;
        DefaultListModel showTime = new DefaultListModel();
        showTimeList.setModel(showTime);
        for (int i = 0; i < actualMovie.getShowtimes().size(); i++) {
            temp = actualMovie.getShowtimes().get(i);
            show = "Date: " + temp.getShowDate() + " Time: " + temp.getShowTime();
            showTime.addElement(show);
        }
        
        movieNameLabel.setText(movieName);
        
        SMDisplay.setVisible(false);
        CADisplay.setVisible(false);
        showTimesDisplay.setVisible(true);
    }//GEN-LAST:event_selectMovieBtnActionPerformed

    private void selectShowTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectShowTimeActionPerformed
        selectSeatPage SP = new selectSeatPage(userEmail);
        SP.setLocationRelativeTo(null);
        SP.setVisible(true);
        dispose();
    }//GEN-LAST:event_selectShowTimeActionPerformed

    private void cancelTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTicketButtonActionPerformed
        enterTicketID ET = new enterTicketID(userEmail);
        ET.setLocationRelativeTo(null);
        ET.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_cancelTicketButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new mainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CAButton;
    private javax.swing.JPanel CADisplay;
    private javax.swing.JRadioButton RBMovie;
    private javax.swing.JPanel SMDisplay;
    private javax.swing.JList<String> accouncementsList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelTicketButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> movieList;
    private javax.swing.JLabel movieNameLabel;
    private javax.swing.JButton selectMovieBtn;
    private javax.swing.JButton selectShowTime;
    private javax.swing.JList<String> showTimeList;
    private javax.swing.JPanel showTimesDisplay;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
