/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;
import java.util.Random;

/**
 *
 * @author karim
 */
public class selectSeatPage extends javax.swing.JFrame {

    private String userEmail;
    public selectSeatPage() {
        initComponents();
    }
    
    public selectSeatPage(String userEMAIL) {
        userEmail = userEMAIL;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        seat2 = new javax.swing.JRadioButton();
        seat4 = new javax.swing.JRadioButton();
        seat3 = new javax.swing.JRadioButton();
        seat6 = new javax.swing.JRadioButton();
        seat5 = new javax.swing.JRadioButton();
        seat7 = new javax.swing.JRadioButton();
        seat8 = new javax.swing.JRadioButton();
        seat9 = new javax.swing.JRadioButton();
        seat10 = new javax.swing.JRadioButton();
        seat11 = new javax.swing.JRadioButton();
        seat12 = new javax.swing.JRadioButton();
        seat13 = new javax.swing.JRadioButton();
        seat14 = new javax.swing.JRadioButton();
        seat15 = new javax.swing.JRadioButton();
        seat16 = new javax.swing.JRadioButton();
        seat17 = new javax.swing.JRadioButton();
        seat18 = new javax.swing.JRadioButton();
        seat1 = new javax.swing.JRadioButton();
        reserveSeatButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        buttonGroup1.add(seat2);
        seat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N
        seat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(seat4);
        seat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat3);
        seat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat6);
        seat6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat5);
        seat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat7);
        seat7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat8);
        seat8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat9);
        seat9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat10);
        seat10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat11);
        seat11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat12);
        seat12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat12.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat13);
        seat13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat13.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat14);
        seat14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat14.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat15);
        seat15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat15.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat16);
        seat16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat16.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat17);
        seat17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat17.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat18);
        seat18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat18.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N

        buttonGroup1.add(seat1);
        seat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seatIcon.png"))); // NOI18N
        seat1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/seatSelectedIcon.png"))); // NOI18N
        seat1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                seat1FocusGained(evt);
            }
        });
        seat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat1ActionPerformed(evt);
            }
        });

        reserveSeatButton.setText("Reserve Seat");
        reserveSeatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveSeatButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(seat7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(seat8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(seat9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(seat10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(seat11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(seat12))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(seat1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(seat2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(seat3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(seat4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(seat5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(seat6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(seat13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seat14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reserveSeatButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seat16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seat17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seat18)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seat6)
                    .addComponent(seat5)
                    .addComponent(seat4)
                    .addComponent(seat3)
                    .addComponent(seat2)
                    .addComponent(seat1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seat12)
                    .addComponent(seat11)
                    .addComponent(seat10)
                    .addComponent(seat9)
                    .addComponent(seat8)
                    .addComponent(seat7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seat18)
                    .addComponent(seat17)
                    .addComponent(seat16)
                    .addComponent(seat15)
                    .addComponent(seat14)
                    .addComponent(seat13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(reserveSeatButton))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat1ActionPerformed
        
    }//GEN-LAST:event_seat1ActionPerformed

    private void seat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat2ActionPerformed

    private void seat1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_seat1FocusGained

    }//GEN-LAST:event_seat1FocusGained

    private void reserveSeatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveSeatButtonActionPerformed
        int seatNumber = 0;
        if (seat1.isSelected()) {
            seatNumber = 1;
        } else if (seat2.isSelected()) {
            seatNumber = 2;
        } else if (seat3.isSelected()) {
            seatNumber = 3;
        } else if (seat4.isSelected()) {
            seatNumber = 4;
        } else if (seat5.isSelected()) {
            seatNumber = 5;
        } else if (seat6.isSelected()) {
            seatNumber = 6;
        } else if (seat7.isSelected()) {
            seatNumber = 7;
        } else if (seat8.isSelected()) {
            seatNumber = 8;
        } else if (seat9.isSelected()) {
            seatNumber = 9;
        } else if (seat10.isSelected()) {
            seatNumber = 10;
        } else if (seat11.isSelected()) {
            seatNumber = 11;
        } else if (seat12.isSelected()) {
            seatNumber = 12;
        } else if (seat13.isSelected()) {
            seatNumber = 13;
        } else if (seat14.isSelected()) {
            seatNumber = 14;
        } else if (seat15.isSelected()) {
            seatNumber = 15;
        } else if (seat16.isSelected()) {
            seatNumber = 16;
        } else if (seat17.isSelected()) {
            seatNumber = 17;
        } else if (seat18.isSelected()) {
            seatNumber = 18;
        }
        
        Random random = new Random();

        int rand = random.nextInt(10000);
        
        if (userEmail == "NONE") {
            movieTicketPayment MTP = new movieTicketPayment(userEmail, seatNumber, rand);
            MTP.setLocationRelativeTo(null);
            MTP.setVisible(true);
            dispose();
        } else {
            receiptPage m = new receiptPage(userEmail, seatNumber, rand);
            m.setLocationRelativeTo(null);
            m.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_reserveSeatButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        mainPage m = new mainPage(userEmail);
        m.setLocationRelativeTo(null);
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectSeatPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectSeatPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectSeatPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectSeatPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectSeatPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reserveSeatButton;
    private javax.swing.JRadioButton seat1;
    private javax.swing.JRadioButton seat10;
    private javax.swing.JRadioButton seat11;
    private javax.swing.JRadioButton seat12;
    private javax.swing.JRadioButton seat13;
    private javax.swing.JRadioButton seat14;
    private javax.swing.JRadioButton seat15;
    private javax.swing.JRadioButton seat16;
    private javax.swing.JRadioButton seat17;
    private javax.swing.JRadioButton seat18;
    private javax.swing.JRadioButton seat2;
    private javax.swing.JRadioButton seat3;
    private javax.swing.JRadioButton seat4;
    private javax.swing.JRadioButton seat5;
    private javax.swing.JRadioButton seat6;
    private javax.swing.JRadioButton seat7;
    private javax.swing.JRadioButton seat8;
    private javax.swing.JRadioButton seat9;
    // End of variables declaration//GEN-END:variables
}
